export const events = [
  {
    title: 'DeveloperWeek 2025',
    image: '/images/event1.png',
    slug: 'developerweek-2025',
    location: 'Santa Clara, CA, USA & Online',
    date: 'February 11 – 13, 2025',
    time: '9:00 AM – 5:00 PM PST Daily',
  },
  {
    title: 'React Miami 2025',
    image: '/images/event2.png',
    slug: 'react-miami-2025',
    location: 'Miami, FL, USA',
    date: 'April 17 – 18, 2025',
    time: '9:30 AM – 6:00 PM EST Daily',
  },
  {
    title: 'PyCon US 2025',
    image: '/images/event3.png',
    slug: 'pycon-us-2025',
    location: 'Pittsburgh, PA, USA',
    date: 'May 14 – 22, 2025',
    time: '8:00 AM – 7:00 PM EDT (Varies by day)',
  },
  {
    title: 'KubeCon + CloudNativeCon Europe 2025',
    image: '/images/event4.png',
    slug: 'kubecon-cloudnative-london-2025',
    location: 'London, UK',
    date: 'April 1 – 4, 2025',
    time: '8:30 AM – 5:30 PM GMT Daily',
  },
  {
    title: 'AWS re:Invent 2025',
    image: '/images/event5.png',
    slug: 'aws-reinvent-2025',
    location: 'Las Vegas, NV, USA',
    date: 'November 25 – 29, 2025',
    time: '8:00 AM – 8:00 PM PST (Includes evening events)',
  },
  {
    title: 'NextJs Conference 2025',
    image: '/images/event6.png',
    slug: 'next-reinvent-2025',
    location: 'Las Vegas, NV, USA',
    date: 'March 25 – 29, 2025',
    time: '8:00 AM – 8:00 PM PST (Includes evening events)',
  },
];
